### ISSUE TITLE
Multi Monitor Configuration

### ISSUE THREAD

**Issue by airgradienthq** [ljagiello/airdash#6]
Achim from AirGradient here. Many thanks for building this.

I have one suggestion. Many people have several monitors on their dashboard and it would be great to add the possibility to define which monitor would be shown.

In our API we have the locationID for this:
https://api.airgradient.com/public/docs/api/v1/#/default/getCurrentMeasures

and the locationID can be seen on our dashboard:
https://app.airgradient.com/settings/location

**Comment by ljagiello** [comment]
Hey @airgradienthq ,

That's a great idea, so far I have only single monitor, but I can absolutely see this being helpful. I will update this issue once I have something working.

**Comment by airgradienthq** [comment]
I have 20 monitors running on my place so it would be reallt great if that could be implemented

**Comment by ljagiello** [comment]
Hey @airgradienthq 

I have added support for `locationId`. Now `airdash` should support configuration with or without `locationId`.

If `locationId` is defined in the configuration, the app will fetch measurements from the selected location. If `locationId` is not defined in the configuration (or uses the default value of `0`), the app will use the previous API path with all locations and select the first one.
