### ISSUE TITLE
json: cannot unmarshal number

### ISSUE THREAD

**Issue by airgradienthq** [ljagiello/airdash#7]
After compiling and running I get this error:

{"time":"2023-10-09T08:30:40.102418+07:00","level":"ERROR","msg":"Parsing JSON payload","error":"json: cannot unmarshal number 53.5 into Go struct field .rhum of type int"}

**Comment by ljagiello** [comment]
Oh, interesting. I guess I incorrectly assumed that under "Measure" (https://api.airgradient.com/public/docs/api/v1/#/), `number` equals `int`. I will check this later today.

**Comment by ljagiello** [comment]
@airgradienthq this issue should be fixed now with https://github.com/ljagiello/airdash/commit/457390445fe18a18afcf36383003935a3363fc81

**Comment by airgradienthq** [comment]
Yes it works now.
![image](https://github.com/ljagiello/airdash/assets/68736665/ec4eb91f-ab75-43c4-8f3f-8cfb5ad6f4b7)

Thanks!
